"""
@Author: li
@Email: lijianqiao2906@live.com
@FileName: adapters.py
@DateTime: 2026-02-09
@Docs: Tortoise ORM adapter helpers.
Tortoise ORM 适配器辅助函数。
"""

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from fastapi_import_export.codecs import BoolCodec, Codec, DateCodec, DatetimeCodec, DecimalCodec, EnumCodec
from fastapi_import_export.exceptions import ImportExportError


def _require_tortoise() -> Any:
    """Ensure Tortoise ORM is importable, otherwise raise ImportExportError.
    确保 Tortoise ORM 可导入，否则抛出 ImportExportError。

    Returns:
        The imported tortoise module.
            导入的 tortoise 模块。

    Raises:
        ImportExportError: When tortoise cannot be imported.
            无法导入 tortoise 时抛出。
    """
    try:
        import tortoise

        return tortoise
    except Exception as exc:  # pragma: no cover
        raise ImportExportError(
            message="Missing optional dependency: tortoise-orm / 缺少可选依赖: tortoise-orm",
            details={"error": str(exc)},
            error_code="missing_dependency",
        ) from exc


def _require_polars() -> Any:
    """Ensure Polars is importable, otherwise raise ImportExportError.
    确保 Polars 可导入，否则抛出 ImportExportError。

    Returns:
        The imported polars module.
            导入的 polars 模块。

    Raises:
        ImportExportError: When polars cannot be imported.
            无法导入 polars 时抛出。
    """
    try:
        import polars as pl

        return pl
    except Exception as exc:  # pragma: no cover
        raise ImportExportError(
            message="Missing optional dependency: polars / 缺少可选依赖: polars",
            details={"error": str(exc)},
            error_code="missing_dependency",
        ) from exc


@dataclass(frozen=True, slots=True)
class FieldSpec:
    """Field specification used by Tortoise models.
    Tortoise 模型使用的字段规范。

    Attributes:
        name: Field name.
            字段名。
        nullable: Whether the field allows null values.
            字段是否允许空值。
        primary_key: Whether this field is a primary key.
            是否为主键。
        generated: Whether this field is generated by DB (e.g., auto-increment).
            是否由数据库生成（例如自增）。
        has_default: Whether the field has a default value.
            是否有默认值。
        python_type: Inferred Python type for the field, or None.
            字段的推断 Python 类型，或 None。
        field: The original Tortoise Field object.
            原始 Tortoise 字段对象。
    """

    name: str
    nullable: bool
    primary_key: bool
    generated: bool
    has_default: bool
    python_type: type[Any] | None
    field: Any


def get_field_specs(model: Any) -> list[FieldSpec]:
    """Extract field specifications for a Tortoise model.
    为 Tortoise 模型提取字段规范。

    Args:
        model: Tortoise model class.
            Tortoise 模型类。
    Returns:
        List[FieldSpec]: List of extracted field specifications.
            提取到的字段规范列表。
    Raises:
        ImportExportError: If model meta information is missing or malformed.
            如果模型 meta 信息缺失或格式不正确则抛出。
    """
    _require_tortoise()
    meta = getattr(model, "_meta", None)
    if meta is None:
        raise ImportExportError(message="Tortoise model missing _meta / 模型缺少 _meta")
    fields_map = getattr(meta, "fields_map", None)
    if not isinstance(fields_map, dict):
        raise ImportExportError(message="Tortoise model fields_map missing / 缺少 fields_map")
    projection = getattr(meta, "fields_db_projection", None)
    if isinstance(projection, dict) and projection:
        field_names = list(projection.keys())
    else:
        field_names = list(fields_map.keys())

    specs: list[FieldSpec] = []
    for name in field_names:
        field = fields_map.get(name)
        if field is None:
            continue
        python_type = getattr(field, "python_type", None)
        specs.append(
            FieldSpec(
                name=str(name),
                nullable=bool(getattr(field, "null", False)),
                primary_key=bool(getattr(field, "pk", False) or getattr(field, "primary_key", False)),
                generated=bool(getattr(field, "generated", False)),
                has_default=getattr(field, "default", None) is not None,
                python_type=python_type if isinstance(python_type, type) else None,
                field=field,
            )
        )
    return specs


def resolve_import_specs(specs: list[FieldSpec], columns: list[str] | None) -> list[FieldSpec]:
    """Resolve import field specifications based on specified columns.
    根据指定的列解析导入字段规范。

    Args:
        specs: List of available FieldSpec objects.
            可用的 FieldSpec 列表。
        columns: Optional list of column names to include.
            可选的要包含的列名列表。
    Returns:
        List[FieldSpec]: Filtered list suitable for import.
            适用于导入的筛选字段规范列表。
    """
    if columns is not None:
        spec_map = {spec.name: spec for spec in specs}
        return [spec_map[name] for name in columns if name in spec_map]
    return [spec for spec in specs if not (spec.primary_key and spec.generated)]


def resolve_export_specs(specs: list[FieldSpec], columns: list[str] | None) -> list[FieldSpec]:
    """Resolve export field specifications based on specified columns.
    根据指定的列解析导出字段规范。

    Args:
        specs: List of available FieldSpec objects.
            可用的 FieldSpec 列表。
        columns: Optional list of column names to include.
            可选的要包含的列名列表。
    Returns:
        List[FieldSpec]: Filtered list suitable for export.
            适用于导出的筛选字段规范列表。
    """
    if columns is not None:
        spec_map = {spec.name: spec for spec in specs}
        return [spec_map[name] for name in columns if name in spec_map]
    return list(specs)


def resolve_field_codecs(model: Any, specs: list[FieldSpec]) -> dict[str, Codec]:
    """Resolve field codecs for a Tortoise model based on field specifications.
    根据字段规范解析 Tortoise 模型的字段编解码器。

    Args:
        model: Tortoise model class.
            Tortoise 模型类。
        specs: FieldSpec list describing fields.
            字段规范列表。
    Returns:
        Mapping from field name to Codec instance.
            字段名到 Codec 实例的映射。
    """
    custom: dict[str, Codec] = {}
    for attr in ("field_codecs", "__import_export_codecs__"):
        value = getattr(model, attr, None)
        if isinstance(value, dict):
            custom.update(value)

    resolved: dict[str, Codec] = {}
    for spec in specs:
        if spec.name in custom:
            resolved[spec.name] = custom[spec.name]
            continue
        codec = _infer_codec(spec)
        if codec is not None:
            resolved[spec.name] = codec
    return resolved


def _infer_codec(spec: FieldSpec) -> Codec | None:
    """Infer a Codec instance for a Tortoise FieldSpec based on type hints.
    根据类型提示为 Tortoise 字段规范推断 Codec 实例。

    Supports Enum/bool/date/datetime/Decimal and field enum_type fallback.
    支持 Enum/bool/date/datetime/Decimal 并回退到字段的 enum_type。

    Args:
        spec: FieldSpec describing the field.
            字段规范。
    Returns:
        Codec instance if one can be inferred, otherwise None.
            若能推断则返回 Codec 实例，否则返回 None。
    """
    py = spec.python_type
    if py is not None and isinstance(py, type):
        if issubclass(py, Enum):
            return EnumCodec(py)
        if py is bool:
            return BoolCodec()
        if py is date:
            return DateCodec()
        if py is datetime:
            return DatetimeCodec()
        if py is Decimal:
            return DecimalCodec()

    enum_type = getattr(spec.field, "enum_type", None)
    if enum_type is not None:
        return EnumCodec(enum_type)
    return None


def cast_basic(value: Any, python_type: type[Any] | None) -> Any:
    """Cast a basic value to the specified Python type.
    将基本值转换为指定的 Python 类型。

    Args:
        value: The value to cast.
        value: 要转换的值。
        python_type: The target Python type, or None to leave unchanged.
        python_type: 目标 Python 类型，或 None 表示保持不变。
    Returns:
        The cast value.
        转换后的值。
    """
    if python_type is None:
        return value
    if python_type is int:
        return int(str(value).strip())
    if python_type is float:
        return float(str(value).strip())
    return value
